### ISSUE TITLE
git commit fails

### ISSUE THREAD

**Issue by Cloudef** [urjaman/dchrt-ng#3]
Git commit seems to fail with output
```
dchrt-ng:~/szdev-recipes/makepnd$ git commit -p
Can't locate Error.pm in @INC (@INC contains: /usr/share/perl/5.8.8 /etc/perl /usr/local/lib/perl/5.8.8 /usr/local/share/perl/5.8.8 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.8 /usr/share/perl/5.8 /usr/local/lib/site_perl   .) at /usr/share/perl/5.8.8/Git.pm line 103.
BEGIN failed--compilation aborted at /usr/share/perl/5.8.8/Git.pm line 103.
Compilation failed in require at /usr/libexec/git-core/git-add--interactive line 7.
BEGIN failed--compilation aborted at /usr/libexec/git-core/git-add--interactive line 7.
fatal: interactive add failed
```

**Comment by urjaman** [comment]
Will look into it, i guess thats only for the interactive mode. Maybe need to install that perl module :P from the sz repo

**Comment by Cloudef** [comment]
Most likely. I can't parse that perl error though :P

**Comment by urjaman** [comment]
Okay so the sz repo doesnt have that perl module (and this thing happens on the original dchrt too, shows how often i use interactive add)

But a "workaround":
 \# opkg install perl-dev
 \# perl -MCPAN -e shell
 ( answer the questionnaire or use the automated one, idk ...)
 cpan> install Error
 (and cpan> quit)

It's a bit hacky-feeling but I think I'll work on doing that (^) automated from the sz-upgrade script as part of the "image"/tarball creation. Atleast it'll make things work and document what was done to make things work.

**Comment by Cloudef** [comment]
I think arch may have package for that too which we can perhaps do recipe for.
